### PR TITLE
Update to latest from Ansible core

### PR DESCRIPTION
**Pull request by AlanCoding**

### CODE REVIEW

**Comment by willtome** [comment]
@AlanCoding shouldn't these options be done using constructed rather than custom/hardcoded functions for creating special groups/variables? see comment https://github.com/theforeman/foreman-ansible-modules/pull/591#issuecomment-588293759

**Comment by AlanCoding** [comment]
I think that the problem with constructed stuff is that it's not really a full language, and replicating the behavior in all circumstances either results in a massive intractable jinja2 soup, or it's just not possible. Some of those issues are with really specific cases, like certain characters. @jladdjr might have more on the motivation for these specific changes.

**Comment by jladdjr** [comment]
I didn't do the testing for this guy originally (and can't find any discussion about using compose on the [original PR](https://github.com/ansible/ansible/pull/66407)). Will take a shot at using compose to handle `want_ansible_ssh_host`.

**Comment by AlanCoding** [comment]
looks like the other one covered this

**Pull request merged**
